name: Build Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos-intel:
    name: Build macOS Executable (Intel)
    runs-on: macos-12 # Intel-based runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (Intel)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller pygame-ce

      - name: Build macOS .app bundle (Intel)
        run: |
          python3 -m PyInstaller \
            --noconfirm --windowed --name "ScoreQuest" \
            --add-data "assets:assets" \
            --add-data "storage:storage" \
            main.py

      - name: Codesign and zip Intel .app
        run: |
          codesign --deep --force --sign - dist/ScoreQuest.app
          xattr -cr dist/ScoreQuest.app
          cd dist
          zip -r ScoreQuest_mac_Intel.zip ScoreQuest.app

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_mac_Intel
          path: dist/ScoreQuest_mac_Intel.zip

  build-macos-silicon:
    name: Build macOS Executable (Silicon)
    runs-on: macos-latest # Apple Silicon runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (Silicon)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyinstaller pygame-ce

      - name: Build macOS .app bundle (Silicon)
        run: |
          python3 -m PyInstaller \
            --noconfirm --windowed --name "ScoreQuest" \
            --add-data "assets:assets" \
            --add-data "storage:storage" \
            main.py

      - name: Codesign and zip Silicon .app
        run: |
          codesign --deep --force --sign "adhoc" dist/ScoreQuest.app
          xattr -cr dist/ScoreQuest.app
          cd dist
          zip -r ScoreQuest_mac_Silicon.zip ScoreQuest.app

      - name: Upload macOS Silicon artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_mac_Silicon
          path: dist/ScoreQuest_mac_Silicon.zip

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r storage/requirements.txt
          pip install pyinstaller pygame-ce

      - name: Build Windows executable
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "ScoreQuest" `
            --add-data "assets;assets" `
            --add-data "storage;storage" `
            main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_win
          path: dist/ScoreQuest.exe
