name: Build macOS Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS Executable
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r storage/requirements.txt
          pip install pyinstaller pygame

      - name: Build macOS executable
        run: |
          pyinstaller --noconfirm --windowed --name "ScoreQuest" \
            --add-data "assets:assets" \
            --add-data "storage:storage" \
            main.py

      - name: Ad-hoc codesign and remove quarantine
        run: |
          codesign --deep --force --sign - dist/ScoreQuest
          xattr -cr dist/ScoreQuest

      - name: Move executable to build folder
        run: |
          mkdir -p build
          mv dist/ScoreQuest build/ScoreQuest_mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_mac
          path: build/ScoreQuest_mac
