name: Build Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos-latest:
    name: Build macOS Executable
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python universal2
        run: |
          curl -LO https://www.python.org/ftp/python/3.11.8/python-3.11.8-macos11-universal2.pkg
          sudo installer -pkg python-3.11.8-macos11-universal2.pkg -target /
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 --version
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -c "import platform; print(platform.machine())"

      - name: Install dependencies
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install --upgrade pip
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install pyinstaller pygame-ce

      - name: Build macOS .app bundle
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m PyInstaller \
            --noconfirm --windowed --name "ScoreQuest" \
            --add-data "assets:assets" \
            --add-data "storage:storage" \
            main.py

      - name: Codesign and zip .app
        run: |
          codesign --deep --force --sign "adhoc" dist/ScoreQuest.app
          xattr -cr dist/ScoreQuest.app
          cd dist
          zip -r ScoreQuest_mac_universal2.zip ScoreQuest.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_mac
          path: dist/ScoreQuest_mac_universal2.zip # use the zipped file here

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r storage/requirements.txt
          pip install pyinstaller pygame-ce

      - name: Build Windows executable
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "ScoreQuest" `
            --add-data "assets;assets" `
            --add-data "storage;storage" `
            main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_win
          path: dist/ScoreQuest.exe
