name: Build Windows Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r storage/requirements.txt
          pip install pyinstaller pygame

      - name: Build Windows executable
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "ScoreQuest" `
            --add-data "assets;assets" `
            --add-data "storage;storage" `
            main.py

      - name: Move executable to build folder
        shell: pwsh
        run: |
          if (-not (Test-Path build)) { New-Item -ItemType Directory -Path build }
          if (Test-Path "dist\ScoreQuest.exe") {
              move dist\ScoreQuest.exe build\ScoreQuest.exe
          } else {
              Write-Host "Executable not found; build may have failed."
              exit 1
          }

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScoreQuest_win
          path: build/ScoreQuest.exe
